name: FOMO_PRODUCTION
options:
  bundleIdPrefix: com.fomoapp
  deploymentTarget:
    iOS: 17.0
  compatibilityVersion:
    iOS: 18.2
  minimumCompatibilityVersion:
    iOS: 17.0
  groupSortPosition: top
  createIntermediateGroups: true
  xcodeVersion: "15.0"
  developmentLanguage: en
targets:
  FOMO_PRODUCTION:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 17.0
    compatibilityVersion:
      iOS: 18.2
    sources:
      - path: FOMO_PRODUCTION
        name: Sources
        excludes:
          - "Assets.xcassets"
          - "Preview Content"
          - "Resources"
          - "FOMO_PRODUCTION_APP"
    resources:
      - path: FOMO_PRODUCTION/Preview Content
        name: Preview Content
        buildPhase: resources
      - path: FOMO_PRODUCTION/Resources
        includes:
          - "**/*.strings"
        buildPhase: resources
    settings:
      base:
        DEVELOPMENT_ASSET_PATHS: ["FOMO_PRODUCTION/Preview Content"]
        PREVIEW_DATA_PATH: "FOMO_PRODUCTION/Preview Content/PreviewData"
        ENABLE_PREVIEWS: YES
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: [DEBUG, PREVIEW, IOS15_COMPAT, IOS17_COMPAT, IOS18_COMPAT]
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "iPhone Distribution"
        DEVELOPMENT_TEAM: "$(DEVELOPMENT_TEAM)"
        PRODUCT_BUNDLE_IDENTIFIER: com.fomoapp.production
        PROVISIONING_PROFILE_SPECIFIER: "match AppStore com.fomoapp.production"
        CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: Combine.framework
      - sdk: Foundation.framework
      - sdk: CoreData.framework
      - sdk: CloudKit.framework
    info:
      path: FOMO_PRODUCTION/Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false

  FOMO_PRODUCTIONTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget:
      iOS: 18.2
    sources:
      - path: FOMO_PRODUCTIONTests
    dependencies:
      - target: FOMO_PRODUCTION
      - framework: XCTest.framework
    settings:
      base:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: [DEBUG, PREVIEW]
        ENABLE_TESTING_SEARCH_PATHS: YES
        GENERATE_INFOPLIST_FILE: YES
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/FOMO_PRODUCTION.app/FOMO_PRODUCTION"

schemes:
  FOMO_PRODUCTION:
    build:
      targets:
        FOMO_PRODUCTION: all
        FOMO_PRODUCTIONTests: [test]
    test:
      targets:
        - name: FOMO_PRODUCTIONTests
          parallelizable: true
          randomExecutionOrder: true
      commandLineArguments:
        "-AppleLanguages": "(en)"
        "-AppleLocale": "en_US"
      environmentVariables:
        SWIFT_DETERMINISTIC_HASHING: YES
    run:
      config: Debug
      commandLineArguments:
        "-preview": true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
