name: FOMO Auto-Deploy

on:
  push:
    branches: [main]
    paths:
      - 'FOMO_PRODUCTION/**'
      - 'FOMO_PRODUCTION/*.xcodeproj/**'
      - 'FOMO_PRODUCTION/*.xcworkspace/**'

jobs:
  build:
    runs-on: macos-latest
    
    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
          
      - name: Install SwiftLint
        run: brew install swiftlint
          
      - name: List files
        run: ls -R FOMO_PRODUCTION
        
      - name: Build Archive
        run: |
          xcodebuild -project FOMO_PRODUCTION/FOMO_PRODUCTION.xcodeproj \
            -scheme FOMO_PRODUCTION \
            -configuration Release \
            -archivePath FOMO_PRODUCTION/FOMO_PRODUCTION.xcarchive \
            clean archive
