name: FOMO Auto-Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: List workspace contents
        run: |
          pwd
          ls -la
          echo "Project structure:"
          find . -name "*.xcodeproj"
          echo "Available schemes:"
          xcodebuild -project ./FOMO_PRODUCTION.xcodeproj -list

      - name: Install dependencies
        run: |
          brew install swiftlint
          brew install xcbeautify

      - name: Build project
        run: |
          xcodebuild clean build \
            -project ./FOMO_PRODUCTION.xcodeproj \
            -scheme "FOMO_PRODUCTION" \
            -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            | xcbeautify

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: ~/Library/Developer/Xcode/DerivedData/
