name: Payment Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up secure environment
      run: |
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
    
    - name: Configure environment
      env:
        SECURE_CONFIG: ${{ secrets.SECURE_CONFIG }}
      run: |
        echo "$SECURE_CONFIG" | base64 --decode > config.enc
        gpg --quiet --batch --yes --decrypt --passphrase="$SECURE_PASSPHRASE" \
          --output .env config.enc
    
    - name: Run validation tests
      run: |
        source .env
        xcodebuild test \
          -scheme FOMO_FINAL \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          -only-testing:FOMO_FINALTests/PaymentValidationTests
      env:
        SECURE_PASSPHRASE: ${{ secrets.SECURE_PASSPHRASE }}

  payment-security:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        
      - name: Install Dependencies
        run: |
          brew install swiftlint
          
      - name: Run SwiftLint
        run: swiftlint --strict FOMO_FINAL/Payment/
        
      - name: Run Tests
        run: |
          swift test --filter PaymentFlowTests/testLiveTokenizationSuccess
          swift test --filter PaymentFlowTests/testSecureURLEnforcement
          ./scripts/validate_tokenization.sh
        env:
          API_KEY: ${{ secrets.PAYMENT_KEY }}
          
      - name: Security Audit
        run: |
          # Check for HTTPS enforcement
          grep -q 'url.scheme == "https"' FOMO_FINAL/Payment/Tokenization/LiveTokenizationService.swift
          
          # Verify keychain usage
          grep -q 'KeychainManager.shared.retrieve(for: .apiKey)' FOMO_FINAL/Payment/Tokenization/LiveTokenizationService.swift 